name: "Terraform plan execution workflow"
on: workflow_dispatch

jobs:
    TerraformCheckout:
        name: "Terraform validate and Terraform Plan"
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
            AWS_REGION: "us-east-1"

        steps:
            - name: "Checkout terraform scripts"
              uses: actions/checkout@v3.5.2
    
            - name: "Setup Terraform on runner"
              uses: hashicorp/setup-terraform@v2.0.3

            - name: "Terraform init"
              run: terraform init

            - name: "Terraform validate"
              run: terraform validate 

            - name: "Terraform plan"
              run: terraform plan
            

